default["smrt_document_root"] = "/srv/www/smrt/current"
default["smrt_db_host_name"] = "sdiu8mt07t471k.clie6s5lawsl.us-east-1.rds.amazonaws.com"
default["smrt_db_username"] = "smrt_db_usr"
default["smrt_db_password"] = "8T01c52909"
default["smrt_db_name"] = "smrt_production"
